apiVersion: v1
kind: Namespace
metadata:
  name: myapp
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
rules:
- apiGroups: ["", "batch", "autoscaling", "extensions", "apps", "events.k8s.io", "metrics.k8s.io", "policy", "networking.k8s.io"]
  resources: ["*"]
#  - "statefulsets"
#  - "horizontalpodautoscalers"
#  - "jobs"
#  - "replicationcontrollers"
#  - "services"
#  - "deployments"
#  - "replicasets"
#  - "pods"
  verbs:  ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-binding
  namespace: myapp
subjects:
- kind: Group
  name: developers
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: developer
  apiGroup: ""
